/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

/**
 *
 * @author Diogo
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        Color fundo = new Color(85,136,236);
        setLocationRelativeTo(null);
        getContentPane().setBackground(fundo);
        
        addPlaceholderStyle(cadastrarRA);
        addPlaceholderStyle(cadastrarSenha);
        addPlaceholderStyle(cadastrarPlaca);
        
    }
    
    public void addPlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    
    public void removePlaceholderStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cadastrarRA = new javax.swing.JTextField();
        cadastrarPlaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cadastrarSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEJA BEM-VINDO(A)!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undraw_Sign_up_n6im-removebg-preview.png"))); // NOI18N

        cadastrarRA.setText("Digite seu RA");
        cadastrarRA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cadastrarRAFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cadastrarRAFocusLost(evt);
            }
        });

        cadastrarPlaca.setText("Digite a placa do carro");
        cadastrarPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cadastrarPlacaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cadastrarPlacaFocusLost(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar-se");

        cadastrarSenha.setText("Digite sua senha");
        cadastrarSenha.setEchoChar('\u0000');
        cadastrarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cadastrarSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cadastrarSenhaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarRA, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(cadastrarRA, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastrarPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarRAFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarRAFocusGained
        // TODO add your handling code here:
        if(cadastrarRA.getText().equals("Digite seu RA")){
            cadastrarRA.setText(null);
            cadastrarRA.requestFocus();
            
            removePlaceholderStyle(cadastrarRA);
        }
    }//GEN-LAST:event_cadastrarRAFocusGained

    private void cadastrarRAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarRAFocusLost
        // TODO add your handling code here:
        if(cadastrarRA.getText().length()== 0){
            addPlaceholderStyle(cadastrarRA);
            
            cadastrarRA.setText("Digite seu RA");
        }
    }//GEN-LAST:event_cadastrarRAFocusLost

    private void cadastrarSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarSenhaFocusGained
        // TODO add your handling code here:
        if(cadastrarSenha.getText().equals("Digite sua senha")){
            cadastrarSenha.setText(null);
            cadastrarSenha.requestFocus();
            
            cadastrarSenha.setEchoChar('\u2022');
            
            removePlaceholderStyle(cadastrarSenha);
        }
    }//GEN-LAST:event_cadastrarSenhaFocusGained

    private void cadastrarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarSenhaFocusLost
        // TODO add your handling code here:
        if(cadastrarSenha.getText().length() == 0){
            addPlaceholderStyle(cadastrarSenha);
            cadastrarSenha.setText("Digite sua senha");
            cadastrarSenha.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_cadastrarSenhaFocusLost

    private void cadastrarPlacaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarPlacaFocusGained
        // TODO add your handling code here:
        if(cadastrarPlaca.getText().equals("Digite a placa do carro")){
            cadastrarPlaca.setText(null);
            cadastrarPlaca.requestFocus();
            
            removePlaceholderStyle(cadastrarPlaca);
        }
    }//GEN-LAST:event_cadastrarPlacaFocusGained

    private void cadastrarPlacaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadastrarPlacaFocusLost
        // TODO add your handling code here:
        if(cadastrarPlaca.getText().length()== 0){
            addPlaceholderStyle(cadastrarPlaca);
            
            cadastrarPlaca.setText("Digite a placa do carro");
        }
    }//GEN-LAST:event_cadastrarPlacaFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cadastrarPlaca;
    private javax.swing.JTextField cadastrarRA;
    private javax.swing.JPasswordField cadastrarSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
